### ISSUE TITLE
[Feature] Self Roles

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#14]
## Use
> People with permission level 2 will be able to add and remove roles from the self roles command, which anyone with any permission level can use the command to get a role.
>
> We should use pagination to show these roles, if there's only one page, no arrow reactions. 
>
> To choose roles i think we should either use reactions like, 0-5, so we limit roles per page, or let the user write the number himself, so we could do something nice like, he writes "1 + 2" it gives the first role and the second, or we could simply limit to 10 reactions, so he can get all 5 roles and remove all 5 if he want as well.
>
> For adding or removing roles from the list we could use flags o3o

**Comment by SpaceEEC** [comment]
Pagination should not be necessary, you can fit ~80 roles (assuming 20 chars per role) in one message.
The message will also be auto truncated if necessary.

Adding roles is probably nicer with their role names (or similar names, see `Resolver#resolveRole`) instead of seemingly "random" numbers or reactions.

Also assigning multiple roles at once instead of one by one seems like a niche, I guess that implementable without too much effort though.

I also think that `selfroles add someRole` is easier than `selfroles --add someRole` for most people.
And flags do not really feel necessary here either.

**Comment by SpaceEEC** [comment]
Completed with
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/dde6fd910861af9c9e457a4bc11f8707f0216411
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/be38bb75a0c5b2cabfe10d79ea9a4415f29ed871
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/8474f5eaf0da712e7752c2f951f1daae056b0f7d
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/7b2d5cf6f3b14de72027ab8aec02578bdbe44dc9
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/813019f60050e75ffe3fa0249a327debfb4d23f3
