### ISSUE TITLE
[BUG HUNT] - Kanna leaderboard level not working.

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#63]
![image](https://user-images.githubusercontent.com/57415893/68244288-6c038900-000c-11ea-844e-70ab9a2ab6e0.png)
![image](https://user-images.githubusercontent.com/57415893/68244301-732a9700-000c-11ea-8c3d-ef8e465baa26.png)

kanna leaderboard level (any offset) does not work.

I did kanna leaderboard level. It did not work.
I also tried it with different offsets, and it did not work.
-CaptMU#2702

**Comment by wizardlink** [comment]
It seems to be an issue with the `level` only, we will take a look as soon as possible.

Also...

> Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] - in the name next time`.

**Comment by SpaceEEC** [comment]
This is because `level` is not defined as valid part in the command, but in its usage:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/user/leaderboard.ts#L16

Looking at the sql below, simply adding `level` there wouldn't work.
What exactly would the difference between `level` and `exp` be, @wizardlink?
Should it just be an alias to `exp` or removed?

**Comment by wizardlink** [comment]
> 
> 
> This is because `level` is not defined as valid part in the command, but in its usage:
> 
> https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/user/leaderboard.ts#L16
> 
> Looking at the sql below, simply adding `level` there wouldn't work.
> What exactly would the difference between `level` and `exp` be, @wizardlink?
> Should it just be an alias to `exp` or removed?

I saw that yesterday, thought it was weird too. As I were in the verge of going to sleep I did not check the database, but almost believed we had a `level` property of user.

Either way, I would think that a level alias would be *good* as it's more intuitive. What do you think?
