### ISSUE TITLE
[BUG HUNT] - Lookup command showing wrong guild

### ISSUE THREAD

**Issue by digitwolfs** [TheDragonProject/Kanna-Kobayashi#64]
<img width="626" alt="Screen Shot 2019-11-05 at 21 42 42" src="https://user-images.githubusercontent.com/46846958/68245076-8478a100-0016-11ea-8652-4f06cef713c1.png">
<img width="643" alt="Screen Shot 2019-11-05 at 21 49 03" src="https://user-images.githubusercontent.com/46846958/68245080-86dafb00-0016-11ea-8cb7-fdd81d3fcc28.png">

[Guild Info]()

## What went wrong
I tried to lookup The Dragon Maid Cult with k!lookup but it only showed info over the server i was using.

## Reproducing the bug

1. I typed kanna lookup
2. Put the invite code after it
3. It didn't show info over the server only the one i was in.

**Comment by wizardlink** [comment]
We will take a look later, thanks for the report. 👍

**Comment by SpaceEEC** [comment]
This is because the `lookup` command calls the `guildinfo` when the requested guild is known to the client (current shard in this case):
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/info/lookup.ts#L39-L40

And the `guildinfo` command always uses the guild of the message:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/info/guild.ts#L23

One way to fix this would be to put the embed building part into another method and call that.
Another way would be to implement a `parseArgs` method setting the `guild` as arg and call the method externally using the requested guild.
